# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.3

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - apt-get update -y
          - apt-get install -y git
          - git clone git@bitbucket.org:project-x-lk/back-office-api.git
          - cd back-office-api
          - mvn clean install
          - cd ..
          - mvn clean package
          - # Whatever else you need.
          - mvn -B verify -DskipTests=false # -B batch mode makes Maven less verbose
