image: pasankavinda/maven-image:latest

pipelines:
  default:
    - step:
        name: Build and Package
        caches:
          - maven
        script:
          - mvn -version
          - mvn clean compile package
        artifacts:
          - target/**

definitions:
  caches:
    maven: ~/.m2
