server.port=8081
## Spring DATA SOURCE
#spring.datasource.url=jdbc:postgresql://dinefy.cs6pov8zgyjc.ap-southeast-1.rds.amazonaws.com/postgres
#spring.datasource.username=dinefy_ro
#spring.datasource.password=dinefy_ro321
spring.datasource.url=jdbc:postgresql://dinefy.cjkcieycezz4.eu-north-1.rds.amazonaws.com/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.jpa.properties.hibernate.default_schema=hngout
spring.datasource.driverClassName=org.postgresql.Driver
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.spatial.dialect.postgis.PostgisDialect
#org.hibernate.spatial.dialect.postgis.PostgisDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
#Disabling contextual LOB creation as createClob() method threw error
#hibernate.temp.use_jdbc_metadata_defaults=false
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
# QUEUE
rabbit.queue.properties.name:queue-properties
# jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Client URL
client.url=http://localhost:4200

# JWT Secret Key
security.jwt.token.secret-key="MySecretKey"