server.port=8080
## Spring DATA SOURCE
spring.datasource.url=jdbc:postgresql://ec2-54-254-85-134.ap-southeast-1.compute.amazonaws.com/hangouts
spring.datasource.username=tharinda
spring.datasource.password=qwerty
spring.jpa.properties.hibernate.default_schema=hngout
spring.datasource.driverClassName=org.postgresql.Driver
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
#org.hibernate.spatial.dialect.postgis.PostgisDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
#Disabling contextual LOB creation as createClob() method threw error
#hibernate.temp.use_jdbc_metadata_defaults=false
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
# QUEUE
rabbit.queue.properties.name:queue-properties
# jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false