server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: dinefy_ro321
    url: jdbc:postgresql://dinefy.cs6pov8zgyjc.ap-southeast-1.rds.amazonaws.com/postgres
    username: dinefy_ro
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: hngout
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: true
    show-sql: true

rabbit:
  queue:
    properties:
      name: queue-properties