name: CI with Maven

on:
  push:
    branches: [ dev-efac ]
  pull_request:
    branches: [ dev-efac ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github  # This should match the ID in your Maven settings.xml for GitHub Packages
          server-username: ${{ github.actor }}  # Default GitHub actor
          server-password: ${{ secrets.MY_GITHUB_TOKEN }}  # Updated token name
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      